version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/fireapp

hooks:
  BeforeInstall:
    - run: |
        sudo apt-get update
        sudo apt-get install -y gnupg curl

        wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org

        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs

  AfterInstall:
    - run: |
        cd /var/www/fireapp

        npm install

  ApplicationStart:
    - run: |
        sudo systemctl start mongod
        sudo systemctl enable mongod

        cd /var/www/fireapp

        npm run start
